install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver

build_script:
  - cmd: build.cmd

after_build:
  - cmd: appveyor PushArtifact "Build\IsValid.%GitVersion_NuGetVersion%.nupkg"